### ISSUE TITLE
Please prove you are human error despite following the instruction

### ISSUE THREAD

**Issue by den1251** [tiesjan/django-hcaptcha-field#10]
Getting `please prove you are human` error despite following the instruction
![image](https://github.com/user-attachments/assets/6e36d199-ff38-4f3d-8bc9-5fb46936824a)
May having a on submit script break it (it was breaking recaptcha V3)? I passed hcaptcha when submitting the form

**Comment by den1251** [comment]
(I passed recaptcha when submitting the form)

**Comment by tiesjan** [comment]
Hi @den1251! A script from the hCaptcha service is included in the HTML page too, so perhaps your script unintentionally interferes with it? With Recaptcha breaking too, perhaps this points to a bug in your script?

The scope of this Django app is the backend and as such does not care _how_ forms are submitted, so I'm afraid I won't be of much help here. Let me know if you find a bug in the backend part.
