### ISSUE TITLE
Why does this package downgrade Django 4.0.3 to 4.0?

### ISSUE THREAD

**Issue by mtbluedog** [tiesjan/django-hcaptcha-field#3]
Why does this package upon installation downgrade Django 4.0.3 to 4.0?
Can it be upgraded to run under 4.0.3?

**Comment by tiesjan** [comment]
Thanks for reporting this. There seems to be some misconfiguration in the `setup.py` file.

**Comment by tiesjan** [comment]
Fixed in version **1.2.2**.

**Comment by mtbluedog** [comment]
Thanks! That works.
